import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Routes, Route } from 'react-router-dom';
import DevelopmentBanner from './components/DevelopmentBanner';
import AnaSayfa from './pages/AnaSayfa';
import GirisYap from './pages/GirisYap';
import KayitOl from './pages/KayitOl';
import Dashboard from './pages/Dashboard';
import DashboardIntegrations from './pages/DashboardIntegrations';
import DashboardAI from './pages/DashboardAI';
import DashboardEFatura from './pages/DashboardEFatura';
import DashboardAnalytics from './pages/DashboardAnalytics';
import DashboardSettings from './pages/DashboardSettings';
import DashboardCustomers from './pages/DashboardCustomers';
import DashboardPayments from './pages/DashboardPayments';
import DashboardProfile from './pages/DashboardProfile';
import DashboardSecurity from './pages/DashboardSecurity';
import DashboardAccounting from './pages/DashboardAccounting';
import DashboardEcommerce from './pages/DashboardEcommerce';
import ProtectedRoute from './components/ProtectedRoute';
import ScrollToTop from './components/ScrollToTop';
// Footer Pages
import ApiDocs from './pages/ApiDocs';
import Roadmap from './pages/Roadmap';
import Esnaf from './pages/solutions/Esnaf';
import Kobi from './pages/solutions/Kobi';
import Vatandas from './pages/solutions/Vatandas';
import Muhasebe from './pages/solutions/Muhasebe';
import Enterprise from './pages/solutions/Enterprise';
import About from './pages/About';
import Blog from './pages/Blog';
import Careers from './pages/Careers';
import Press from './pages/Press';
import Contact from './pages/Contact';
import Privacy from './pages/Privacy';
import Terms from './pages/Terms';
import Cookies from './pages/Cookies';
import Disclosure from './pages/Disclosure';
import Security from './pages/Security';
import Help from './pages/Help';
import Support from './pages/Support';
import Faq from './pages/Faq';
import Tutorials from './pages/Tutorials';
import Community from './pages/Community';
function App() {
    return (_jsxs(_Fragment, { children: [_jsx(DevelopmentBanner, {}), _jsx("div", { className: "gradient-mesh-bg", "aria-hidden": "true" }), _jsxs("div", { className: "relative z-10 pt-12", children: [_jsx(ScrollToTop, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(AnaSayfa, {}) }), _jsx(Route, { path: "/giris-yap", element: _jsx(GirisYap, {}) }), _jsx(Route, { path: "/kayit-ol", element: _jsx(KayitOl, {}) }), _jsx(Route, { path: "/panel", element: _jsx(ProtectedRoute, { children: _jsx(Dashboard, {}) }) }), _jsx(Route, { path: "/panel/entegrasyonlar", element: _jsx(ProtectedRoute, { children: _jsx(DashboardIntegrations, {}) }) }), _jsx(Route, { path: "/panel/ai-asistan", element: _jsx(ProtectedRoute, { children: _jsx(DashboardAI, {}) }) }), _jsx(Route, { path: "/panel/faturalar", element: _jsx(ProtectedRoute, { children: _jsx(DashboardEFatura, {}) }) }), _jsx(Route, { path: "/panel/raporlar", element: _jsx(ProtectedRoute, { children: _jsx(DashboardAnalytics, {}) }) }), _jsx(Route, { path: "/panel/ayarlar", element: _jsx(ProtectedRoute, { children: _jsx(DashboardSettings, {}) }) }), _jsx(Route, { path: "/panel/musteriler", element: _jsx(ProtectedRoute, { children: _jsx(DashboardCustomers, {}) }) }), _jsx(Route, { path: "/panel/odemeler", element: _jsx(ProtectedRoute, { children: _jsx(DashboardPayments, {}) }) }), _jsx(Route, { path: "/panel/profil", element: _jsx(ProtectedRoute, { children: _jsx(DashboardProfile, {}) }) }), _jsx(Route, { path: "/panel/guvenlik", element: _jsx(ProtectedRoute, { children: _jsx(DashboardSecurity, {}) }) }), _jsx(Route, { path: "/panel/2fa", element: _jsx(ProtectedRoute, { children: _jsx(DashboardSecurity, {}) }) }), _jsx(Route, { path: "/panel/muhasebe", element: _jsx(ProtectedRoute, { children: _jsx(DashboardAccounting, {}) }) }), _jsx(Route, { path: "/panel/e-ticaret", element: _jsx(ProtectedRoute, { children: _jsx(DashboardEcommerce, {}) }) }), _jsx(Route, { path: "/api-docs", element: _jsx(ApiDocs, {}) }), _jsx(Route, { path: "/roadmap", element: _jsx(Roadmap, {}) }), _jsx(Route, { path: "/solutions/esnaf", element: _jsx(Esnaf, {}) }), _jsx(Route, { path: "/solutions/kobi", element: _jsx(Kobi, {}) }), _jsx(Route, { path: "/solutions/vatandas", element: _jsx(Vatandas, {}) }), _jsx(Route, { path: "/solutions/muhasebe", element: _jsx(Muhasebe, {}) }), _jsx(Route, { path: "/solutions/enterprise", element: _jsx(Enterprise, {}) }), _jsx(Route, { path: "/about", element: _jsx(About, {}) }), _jsx(Route, { path: "/blog", element: _jsx(Blog, {}) }), _jsx(Route, { path: "/careers", element: _jsx(Careers, {}) }), _jsx(Route, { path: "/press", element: _jsx(Press, {}) }), _jsx(Route, { path: "/contact", element: _jsx(Contact, {}) }), _jsx(Route, { path: "/privacy", element: _jsx(Privacy, {}) }), _jsx(Route, { path: "/terms", element: _jsx(Terms, {}) }), _jsx(Route, { path: "/cookies", element: _jsx(Cookies, {}) }), _jsx(Route, { path: "/disclosure", element: _jsx(Disclosure, {}) }), _jsx(Route, { path: "/security", element: _jsx(Security, {}) }), _jsx(Route, { path: "/help", element: _jsx(Help, {}) }), _jsx(Route, { path: "/support", element: _jsx(Support, {}) }), _jsx(Route, { path: "/faq", element: _jsx(Faq, {}) }), _jsx(Route, { path: "/tutorials", element: _jsx(Tutorials, {}) }), _jsx(Route, { path: "/community", element: _jsx(Community, {}) })] })] })] }));
}
export default App;
